version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch-new
    restart: always
    volumes:
      - /home/niket/elk_stack/single_node_elk/elk:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk

  Logstash:
    image: logstash:7.16.2
    container_name: logstash-new
    restart: always
    volumes:
      - /home/niket/elk_stack/single_node_elk/logstash:/tmp  # replace "/home/kali/ws/elk with log directory "
    command: logstash -f /tmp/logstash.conf 
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      INPUT_PATH: "/tmp/rubikxv3.log"
      OUTPUT_ELASTICSEARCH_HOST: "192.168.29.161"
      OUTPUT_ELASTICSEARCH_PORT: "9200"
      OUTPUT_INDEX_PREFIX: "test"
    networks:
      - elk

  Kibana:
    image: kibana:7.16.2
    container_name: kibana-new
    restart: always       
    ports:
      - '5601:5601'
    depends_on:
      - Elasticsearch  
    networks:
      - elk

volumes:
  elastic_data: {}

networks:
  elk:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16  
          gateway: 172.24.0.1

