version: '3.6'
services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch-new
    restart: always
    volumes:
      - /home/niket/elk_stack/muti_node_elk/master/elk:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - elk
  Kibana:
    image: kibana:7.16.2
    container_name: kibana-new
    restart: always
    ports:
      - '5601:5601'
    depends_on:
      - Elasticsearch
    networks:
      - elk

volumes:
  elastic_data: {}

networks:
  elk:
